### PR TITLE
Add operators

### PR DESCRIPTION
**Pull request by inkytonik**
A first go at adding some more user-friendly syntax in the form of operators and if-then-else.

- Add syntax for the following operators:
-- +, *, -, /, %, ** (arithmetic)
-- ++ (string or vector concatentation)
-- prefix !, &&, || (logical)
-- ==, != (equality)
-- <, <=, >, >= (relational)
-- binary ! (vector index)
-- wrap-around |_| (int abs, string and vector length)

- Add if-then-else syntax.

- Add ite (if-then-else) function to default prelude. Use it in the implementations of and, not and or.

- Change variant syntax to <<...>> to avoid parsnig issue with relational operators.

- Add desugaring pass to turn operator syntax into prelude calls, eg a + b turns into Ints.add(a, b). if-then-else turns into ite. In theory, someone can provide a new prelude that implements these functions in a new way and thereby redefine what the operators do.

- Add int mod primitive and Ints.mod prelude function.

- Add -D option to print out desugared AST and desguaredtree product to Server.

- Avoid node sharing when creating representations of basic types, eg strT now makes a new node rather than returning same one each time. This avoids some issues where the node would appear in different places in the AST.

- Move from passing strings to passing primitives for error messages etc.

- Improve semantic analysis errors for record concat to include the thing we got, as in the other type errors.

- Rename PredefFunctionEntity to PredefTypeEntity since that matches more its purpose.

- Add semantic and execution OperatorTests. Some extension and reorg of ExecutionTest to facilitate new tests.

### CODE REVIEW

**Review by nhweston — COMMENTED** [review]
A few issues:

### Type inference of `==`

Are we okay with this behaviour?:

```
cooma> { a = 1 } == { a = 1, b = 1 }
res24 : << False : Unit, True : Unit >> = << True = {} >>
```

### Plinging an empty vector

Strange error message printed when plinging an empty vector:

```
cooma> [] ! 0
1:1:error: illegal Vector()!, only Vector supported
[] ! 0
^
```

### Nested if-then-else causes crash

An if-then-else as the _then_ expression causes a crash:

```
cooma> if true then if true then 0 else 1 else 2
Exception in thread "main" java.lang.IllegalStateException: Cycle detected in attribute evaluation at IdnUse(Int)
	at org.bitbucket.inkytonik.kiama.attribution.Attribute.reportCycle(Attribute.scala:24)
	at org.bitbucket.inkytonik.kiama.attribution.Attribution$CachedAttribute.apply(Attribution.scala:57)
	at org.bitbucket.inkytonik.kiama.attribution.Decorators.indflt$1(Decorators.scala:126)
	at org.bitbucket.inkytonik.kiama.attribution.Decorators.$anonfun$chain$3(Decorators.scala:135)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser$$anonfun$envin$1.applyOrElse(SemanticAnalyser.scala:288)
…
```

However, an if-then-else in the _else_ block works fine:

```
cooma> if true then 0 else if true then 1 else 2
res0 : Int = 0
```

**Comment by symbiont-tony-sloane** [comment]
Thanks for catching those problems. Obviously, my testing left something to be desired in my haste to get it sorted :-)

The record equality one is a bit weird, not sure what's happening there yet.

The pling one is a missing case, it should be allowed (to then fail at runtime).

And I think I know what happened in the if-then-else one since I had a similar crash from another situation. Sometimes we need to clone some types to avoid them appearing in multiple places in the tree. Adding a clone in the right place should fix that.

**Comment by nhweston** [comment]
Wouldn't the record equality be due to the inference of the type parameter of `==` as `{ a : Int }`, so only `a` is checked for equality?

**Comment by nhweston** [comment]
LGTM.

**Pull request merged**
